[bindings.kotlin]
package_name = "dev.damsac.{{project_underscore}}.rust"
cdylib_name = "{{project_underscore}}_ffi"

[bindings.swift]
module_name = "{{ProjectPascal}}Core"
cdylib_name = "{{project_underscore}}_ffi"
